### ISSUE TITLE
Gem release?

### ISSUE THREAD

**Issue by jessieay** [square/fdoc#63]
I was having some issues generating docs with fdoc this morning. When I went source diving, I noticed that my local files did not match what is on GitHub. Specifically, the check for RSpec 3 here: https://github.com/square/fdoc/blob/fc692a23ed7bb3536663b7e1edf5706617c9758a/lib/fdoc/spec_watcher.rb#L38

When I went to compare the git history and gem releases, I saw that the gem was last released in November 2011 https://rubygems.org/gems/fdoc

Is there a reason for this? A new release would be awesome!

**Comment by zachmargolis** [comment]
No good reason! I'll push a gem version now.

**Comment by zachmargolis** [comment]
Pushed `v.0.3.3`
